[project]
name = "danish-democracy-data"
version = "0.1.0"
description = "Open source project pulling data from the Danish Parliament API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.9.3",
    "dbt-duckdb>=1.9.2",
    "dlt>=1.8.0",
    "ruff>=0.9.10",
]
